debug

diff --git a/.github/workflows/release-edge-tag.yml b/.github/workflows/release-edge-tag.yml
--- a/.github/workflows/release-edge-tag.yml
+++ b/.github/workflows/release-edge-tag.yml
@@ -6,25 +6,27 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: update release-edge tag
-        if: |
-          github.event.issue.pull_request &&
-          github.event.pull_request.head.ref == 'release-edge' &&
-          startsWith(github.event.comment.body, 'release-edge-')
+#        if: |
+#          github.event.issue.pull_request &&
+#          github.event.pull_request.head.ref == 'release-edge' &&
+#          startsWith(github.event.comment.body, 'release-edge-')
         run: |
-          ECR_REGISTRY=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com
-          aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login -u AWS --password-stdin ${ECR_REGISTRY}
-          if [[ "${GITHUB_REF#refs/tags/}" =~ ^release-edge-(r[0-9]{8})$ ]]; then
-            image_tag=${BASH_REMATCH[1]}
-          fi
-          if [[ -z "${image_tag}" ]]; then
-            echo "image tag not found"
-            exit 1
-          fi
-          image_url=${ECR_REGISTRY}/${ECR_REPOSITORY}
-          docker pull ${image_url}:${image_tag}
-          docker tag ${image_url}:${image_tag} ${image_url}:release-edge
-          docker push ${image_url}:release-edge
+          echo "$GITHUB_CONTEXT"
+#          ECR_REGISTRY=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com
+#          aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login -u AWS --password-stdin ${ECR_REGISTRY}
+#          if [[ "${GITHUB_REF#refs/tags/}" =~ ^release-edge-(r[0-9]{8})$ ]]; then
+#            image_tag=${BASH_REMATCH[1]}
+#          fi
+#          if [[ -z "${image_tag}" ]]; then
+#            echo "image tag not found"
+#            exit 1
+#          fi
+#          image_url=${ECR_REGISTRY}/${ECR_REPOSITORY}
+#          docker pull ${image_url}:${image_tag}
+#          docker tag ${image_url}:${image_tag} ${image_url}:release-edge
+#          docker push ${image_url}:release-edge
         env:
+          GITHUB_CONTEXT: ${{ toJson(github) }}
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
